name: Var Global Variable  # ðŸ‘ˆ This sets the display name in GitHub Actions

on:
  workflow_dispatch

env:
  MY_LOCAL_VAR: workflow

jobs:
  variables:
    env:
      MY_LOCAL_VAR: Hello jobs
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo '${{ env.MY_LOCAL_VAR }}'
          echo '${{ var.MY_GLOBAL_VAR }}'
        env:
          MY_LOCAL_VAR: Hello Steps
